apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{.Values.name}}
  name: {{.Values.name}}
spec:
  replicas: {{.Values.scale}}
  selector:
    matchLabels:
      app: {{.Values.name}}
  template:
    metadata:
      labels:
        app: {{.Values.name}}
    spec:
      containers:
      - image: nginx:{{.Values.tag}}
        name: {{.Values.name}}
        ports:
          - containerPort: 80

