apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngnix
spec:
  replicas: {{.Values.scale}}
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx: {{.Values.tag}}
          ports:
            - containerPort: 80
