apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{.Values.ingressname}}
spec:
  rules:
  - host: {{.Values.domain}}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{.Values.name}}
            port: 
              number: {{.Values.port}}
  ingressClassName: nginx
---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: {{.Values.name}}
spec:
  controller: k8s.io/ingress-nginx
